### ISSUE TITLE
what is the status of this proposal?  Was this proposal accepted?

### ISSUE THREAD

**Issue by ghost** [msaboff/JavaScript-Standard-Library#69]
Hello.

I would like to know if this proposal was made or accepted. 
- Was this proposal made or accepted?
- what is the status of this proposal?
- does current javascript already implement proposal: proposal-built-in-modules?

**Comment by phryneas** [comment]
It's Stage 1 and was last discussed [September 2020](https://github.com/tc39/notes/blob/HEAD/meetings/2020-09/sept-24.md#builtin-modules-for-stage-2)

**Comment by ljharb** [comment]
It was made, it's stage 1, as you can see here: https://github.com/tc39/proposals/blob/main/stage-1-proposals.md

It's way too early to implement any proposal before stage 3, and before stage 2, the spec isn't even sufficient to do so, so no, nobody's implemented it.

#3 may also be useful.
